services:
  hyper-event-app:
    container_name: hyper-event-app
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
      - ./app:/opt/www/app
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
networks:
  default:
    name: hyperf-skeleton
