services:
  hyperf:
    build: .
    container_name: hyperf_app
    working_dir: /opt/www
    volumes:
      - .:/opt/www
    ports:
      - "9501:9501"
    command: ["sh", "-c", "composer install && php /opt/www/bin/hyperf.php server:watch"]
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TIMEZONE=UTC
    # command: sh -c "composer install && php bin/hyperf.php start"
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
networks:
  default:
    name: hyperf-skeleton
