services:
  hyperf:
#    user: "${UID:-1000}:${GID:-1000}"
    user: "0:0"
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        BUILD_ENV: ${APP_ENV:-prod}
    container_name: hyperf_app
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - APP_ENV=${APP_ENV:-prod}
      - SCAN_CACHEABLE=${SCAN_CACHEABLE:-true}
      - WATCH_ENABLE=${WATCH_ENABLE:-false}
      - WATCH_DIR=${WATCH_DIR:-app,config}
      - WATCH_EXT=${WATCH_EXT:-php,env}
      - WATCH_DELAY=${WATCH_DELAY:-0.5}
      - REDIS_HOST=redis
    volumes:
      - ${APP_CODE_PATH_HOST:-./}:${APP_CODE_PATH_CONTAINER:-/var/www/html}:${APP_CODE_CONTAINER_FLAG:-cached}
      - ./storage/logs:/var/www/html/runtime/logs:rw
      - ./vendor:/var/www/html/vendor:cached
    ports:
      - "${APP_PORT:-9501}:9501"
    depends_on:
      - mysql
      - redis
    command: ${HYPERF_COMMAND:-php bin/hyperf.php start}
    tty: ${TTY_ENABLE:-false}

  mysql:
    image: mysql:8.0
    container_name: hyperf_mysql
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-hyperf}
      - MYSQL_USER=${DB_USERNAME:-hyperf}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "${DB_PORT:-3306}:3306"

    user: "${UID:-1000}:${GID:-1000}"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
networks:
  default:
    name: hyperf
volumes:
  mysql_data: